apiVersion: v1
kind: Service
metadata:
  name: kde-apiserver
  namespace: system
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: kde-apiserver
