apiVersion: linuxsuren.github.io/v1alpha1
kind: DevSpace
metadata:
  labels:
    app.kubernetes.io/name: kde
    app.kubernetes.io/managed-by: kustomize
  name: devspace-sample
spec:
  services:
    docker:
      enabled: true
      registryMirrors:
        - https://docker.m.daocloud.io
      insecureRegistries:
        - 192.168.0.100:5000
      maxConcurrentUploads: 10
      maxConcurrentDownloads: 10
